### ISSUE TITLE
How to proceed with the launchpad pro

### ISSUE THREAD

**Issue by faroit** [RocketScienceAbteilung/novation-launchpad-pro#7]
### Status

The original bitwig launchpad implementation looks not very promising. Althought it works with the launchpad pro now there are many bugs to fix. Also the source code base is not very organised which makes it difficult to support new features and pages (which would make sense, since the launchpad pro has way more buttons).
### What to do

I would propose to not proceed with this project but instead make a new one which is build on top of https://github.com/teotigraphix/Framework4Bitwig (maybe their authors are interested in joining).

Would be great to hear about what other people think

**Comment by micahscopes** [comment]
This sounds great.  I'd love to contribute however I can.

My intention is to go 'off-road' and play with some experimental user interface ideas.

For example: I'd like to try using aftertouch to control faders and knobs.  So say you pressed on a pad designated to change the volume of a track.  As you pressed it, the aftertouch would be mapped to volume.  If you let go, it would go back to the volume without saving the changes.  But if you pressed the triangle button or maybe the circle button, it would write the volume.  If you were recording, you could hold the circle button as you changed pressure on the pad.  This would keep writing volume to an automation channel.

I'd like to play with this concept similarly for macro knobs, etc.

**Comment by micahscopes** [comment]
I was just looking at Framework4Bitwig.   Can you tell something about why you'd like to use it over the bare API?  This is my first time working with the Bitwig Controller API, so I'm unfamiliar with its strengths and shortcomings.

**Comment by micahscopes** [comment]
I just saw the Scales object... :+1:   That alone seems like good reason to use Framework4Bitwig

**Comment by faroit** [comment]
;-) The bare API is fine as longs the software is not becoming too complex.
E.g. look at how pages stuff is implemented in https://github.com/RocketScienceAbteilung/novation-launchpad-pro/blob/master/launchpad_grid.js#L28 it's a mess. The Framework4Bitwig seems to have a nicely done abstraction of pages/views.

**Comment by micahscopes** [comment]
Yup... looks a little bit haphazard!

I fonud a good, concise video on how the launchpad pro is "supposed" to work in Ableton.  https://youtu.be/8xPyYZMmi5o?t=1m10s

**Comment by micahscopes** [comment]
Well, after playing with this controller, I don't think I'm gonna keep it unless they add some way to tune the minimum pad sensitivity...  I got it because it was marketed as a performance instrument.  But at the minimum pressures required to hold the pads on, my hands don't perform well anymore.

That said, before I take it back to the store (I have two months), I'll try and mess with the aftertouch -> parameter mappings.  I think those could be really useful!  And maybe I'll fix a few bugs too.

**Comment by faroit** [comment]
actually the source code of the ableton mapping is revealed here: https://github.com/gluon/AbletonLive9_RemoteScripts/tree/master/Launchpad_Pro 

The threshold thing: Funny. See my comment [here](https://github.com/dvhdr/launchpad-pro/issues/6)

**Comment by faroit** [comment]
Seems like the guys from gitmoss did release a controller script based on their framework: https://github.com/git-moss/LaunchpadPro4Bitwig

Therefore I will shut this project down since the other project is far more advanced
