### ISSUE TITLE
Documentation for Testing

### ISSUE THREAD

**Issue by diemonster** [RocketScienceAbteilung/novation-launchpad-pro#8]
This may be a premature request, but it would be useful to have some documentation that outlines how this controller works (or will work) with Bitwig. 

For example:
- Are you planning to borrow the workflow from [Push](https://github.com/git-moss/Push4Bitwig) or Ableton Live 9's Launchpad Pro implementation? 

At this point, I have the Launchpad Pro recognized in Bitwig 1.2 beta 7, and the various modes seem to register within Bitwig. However, how those modes (clip launcher, step sequencer, etc) map onto functionality is a mystery.

**Comment by faroit** [comment]
@diemonster thanks so such for your input. Currently the workflow is the same as for [Bitwigs standard launchpad implementation](https://github.com/bitwig/novation-launchpad). So you will find the documentation there. 

But:

Yes I think I will not continue doing this the implementation mentioned above is not very easy too maintain and lacks a lot of documentation in the code as well. Before starting (I will have some more free time in 2 weeks I will contact the @git-moss guys to check if they are interested to help out.

**Comment by diemonster** [comment]
Thank you @faroit, very excited to see what you come up with! Agreed that Bitwig's implementation is difficult; I can certainly see the appeal of taking an [alternate](https://github.com/teotigraphix/Framework4Bitwig) direction.
